<?php
/**
 * Copyright (C) Youthweb e.V. 2004 - 2016
 * All rights reserved.
 */

namespace Youthweb\SmileyEmojiMigration;

/**
 * README.md parser
 */

class Converter
{
	/**
	 * export as json
	 */
	public function toJsonFile($file_path)
	{
		$file_path = realpath($file_path);

		$data = $this->createJson(JSON_PRETTY_PRINT);

		file_put_contents($file_path, $data);
	}

	/**
	 * export as JS file
	 */
	public function toJavaScriptFile($file_path)
	{
		$file_path = realpath($file_path);

		$data = $this->createJson(JSON_PRETTY_PRINT);

		$content = sprintf('var youthweb_smilies = %s;', $data);

		file_put_contents($file_path, $content);
	}

	/**
	 * export as node module
	 */
	public function toNodeModule($file_path)
	{
		$file_path = realpath($file_path);

		$data = $this->createJson(JSON_PRETTY_PRINT);

		$module_template = '/* THIS FILE IS AUTOGENERATED! DO NOT EDIT! */
export default function()
{
    this.smileylist = %s;
};
';

		$content = sprintf($module_template, $data);

		file_put_contents($file_path, $content);
	}

	private function createJson($json_options = 0)
	{
		$parser = new Parser();

		$data = [];

		$raw = $parser->parseReadme();

		foreach ($raw as $raw_part)
		{
			if ( count($raw_part['unicodes']) === 0 )
			{
				$unicode = $raw_part['smiley_code'];
				$is_smiley = true;
				$file_name = $raw_part['smiley_filename'];
			}
			else
			{
				$unicode = implode('-', $raw_part['unicodes']);
				$is_smiley = false;
				$file_name = '';
			}

			$data_set = [
				'isCanonical' => false,
				'isSmiley' => $is_smiley,
				'unicode' => [$unicode],
				'filename' => $file_name,
			];

			$data[$raw_part['smiley_code']] = $data_set;
		}

		return json_encode($data, $json_options);
	}
}
