/* THIS FILE IS AUTOGENERATED! DO NOT EDIT! */
export default function()
{
    this.smileylist = {
    ":fischer:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3a3"
        ],
        "filename": ""
    },
    ":sleep:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f634"
        ],
        "filename": ""
    },
    ":angst:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f628"
        ],
        "filename": ""
    },
    ":gworsky:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f483"
        ],
        "filename": ""
    },
    ":streiten:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f4a2"
        ],
        "filename": ""
    },
    ":baby:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f476"
        ],
        "filename": ""
    },
    ":birthday:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f382"
        ],
        "filename": ""
    },
    ":bounce:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f603"
        ],
        "filename": ""
    },
    ":buck:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f61d"
        ],
        "filename": ""
    },
    ":confused:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f615"
        ],
        "filename": ""
    },
    ":heul:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f62d"
        ],
        "filename": ""
    },
    ":gg:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f600"
        ],
        "filename": ""
    },
    ":king:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f451"
        ],
        "filename": ""
    },
    ":krach:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f621"
        ],
        "filename": ""
    },
    ":kreisen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f643"
        ],
        "filename": ""
    },
    ":lol:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f606"
        ],
        "filename": ""
    },
    ":leaa:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "270c-1f600-270c"
        ],
        "filename": ""
    },
    ":esta:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":esta:"
        ],
        "filename": "496.gif"
    },
    ":mecker:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "261d-1f620"
        ],
        "filename": ""
    },
    ":band:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3a4-1f3b8"
        ],
        "filename": ""
    },
    ":music:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3a7"
        ],
        "filename": ""
    },
    ":band2:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3bb-1f3b8"
        ],
        "filename": ""
    },
    ":nervensaege:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3bb"
        ],
        "filename": ""
    },
    ":dj:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":dj:"
        ],
        "filename": "dj.gif"
    },
    ":birthday3:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f388"
        ],
        "filename": ""
    },
    ":schulstreit:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":schulstreit:"
        ],
        "filename": "059.gif"
    },
    ":lesen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f4da"
        ],
        "filename": ""
    },
    ":rofl:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f923"
        ],
        "filename": ""
    },
    ":-)": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "263a"
        ],
        "filename": ""
    },
    ":super:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f609-1f44d"
        ],
        "filename": ""
    },
    ":ww:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f44b"
        ],
        "filename": ""
    },
    ":blinz:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f609"
        ],
        "filename": ""
    },
    ":crazy:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f61c"
        ],
        "filename": ""
    },
    ":morgen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f634-1f304"
        ],
        "filename": ""
    },
    ":giveup:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3f3"
        ],
        "filename": ""
    },
    ":kruecken:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f915"
        ],
        "filename": ""
    },
    ":essen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f374"
        ],
        "filename": ""
    },
    ":fernsehn:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f6cb-1f4fa"
        ],
        "filename": ""
    },
    ":duschen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f6bf"
        ],
        "filename": ""
    },
    ":abwasch:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":abwasch:"
        ],
        "filename": "abwasch.gif"
    },
    ":arbeiten:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f528"
        ],
        "filename": ""
    },
    ":toilette:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f6bd"
        ],
        "filename": ""
    },
    ":sdu8:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f60e"
        ],
        "filename": ""
    },
    ":arab:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f473"
        ],
        "filename": ""
    },
    ":mcdonalds:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f354-1f35f"
        ],
        "filename": ""
    },
    ":boxen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f94a"
        ],
        "filename": ""
    },
    ":verr\u00fcckt:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f44a"
        ],
        "filename": ""
    },
    ":urlaub:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3c4"
        ],
        "filename": ""
    },
    ":victory:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "270c"
        ],
        "filename": ""
    },
    ":liebesbrief:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f48c"
        ],
        "filename": ""
    },
    ":weinen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f62d"
        ],
        "filename": ""
    },
    ":gucken:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":gucken:"
        ],
        "filename": "00000952[1].gif"
    },
    ":pcprob:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f4bb-1f620-1f44a"
        ],
        "filename": ""
    },
    ":waschen2:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f455-1f6bf"
        ],
        "filename": ""
    },
    ":koch:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f373"
        ],
        "filename": ""
    },
    ":baden:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f6c0"
        ],
        "filename": ""
    },
    ":troesten:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f917"
        ],
        "filename": ""
    },
    ":b\u00fcgeln:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":b\u00fcgeln:"
        ],
        "filename": "buegeln.gif"
    },
    ":respekt:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":respekt:"
        ],
        "filename": "288.gif"
    },
    ":naund:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":naund:"
        ],
        "filename": "00000673.gif"
    },
    ":doof:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":doof:"
        ],
        "filename": "doof.gif"
    },
    ":ethe:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ethe:"
        ],
        "filename": "blumen.gif"
    },
    ":pascholti:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":pascholti:"
        ],
        "filename": "paschol.png"
    },
    ":love1:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f491"
        ],
        "filename": ""
    },
    ":boxen2:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f93c"
        ],
        "filename": ""
    },
    ":aldi:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":aldi:"
        ],
        "filename": "aldi.gif"
    },
    ":mama:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f469"
        ],
        "filename": ""
    },
    ":bye:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f44b"
        ],
        "filename": ""
    },
    ":birthday2:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f38a"
        ],
        "filename": ""
    },
    ":eingebildet:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f633"
        ],
        "filename": ""
    },
    ":bipa:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":bipa:"
        ],
        "filename": "spassbremse.gif"
    },
    ":gewalt:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":gewalt:"
        ],
        "filename": "Gewalt.gif"
    },
    ":kopfschlag:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f926"
        ],
        "filename": ""
    },
    ":look:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":look:"
        ],
        "filename": "atanz2.gif"
    },
    ":noterror:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":noterror:"
        ],
        "filename": "noterror.gif"
    },
    ":schleimer:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":schleimer:"
        ],
        "filename": "schleimer.gif"
    },
    ":gassi:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":gassi:"
        ],
        "filename": "smilie_hund1.gif"
    },
    ":heck:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":heck:"
        ],
        "filename": "heck.gif"
    },
    ":baseball:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "26be"
        ],
        "filename": ""
    },
    ":heuldoch:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":heuldoch:"
        ],
        "filename": "heuldoch.gif"
    },
    ":gutenacht:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f303"
        ],
        "filename": ""
    },
    ":weck": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":weck"
        ],
        "filename": "62.gif"
    },
    ":bussi:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f48f"
        ],
        "filename": ""
    },
    ":sani:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f691"
        ],
        "filename": ""
    },
    ":worship:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":worship:"
        ],
        "filename": "a030.gif"
    },
    ":regin:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":regin:"
        ],
        "filename": "a035.gif"
    },
    ":campen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "26fa"
        ],
        "filename": ""
    },
    ":inlove:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f46b"
        ],
        "filename": ""
    },
    ":rockon:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3b8"
        ],
        "filename": ""
    },
    ":reiten:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3c7"
        ],
        "filename": ""
    },
    ":kotz:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f637"
        ],
        "filename": ""
    },
    ":pfeifen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":pfeifen:"
        ],
        "filename": "a050.gif"
    },
    ":feierabend:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":feierabend:"
        ],
        "filename": "feierabend.gif"
    },
    ":danke:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":danke:"
        ],
        "filename": "Danke.gif"
    },
    ":dagegen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":dagegen:"
        ],
        "filename": "dagegen.gif"
    },
    ":frauenpower:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":frauenpower:"
        ],
        "filename": "frauen_power.gif"
    },
    ":bitte:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":bitte:"
        ],
        "filename": "bbitte.gif"
    },
    ":gibtnix:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":gibtnix:"
        ],
        "filename": "gibtnix.gif"
    },
    ":wiejetzt:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":wiejetzt:"
        ],
        "filename": "haewiejetzt.gif"
    },
    ":hilfe:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":hilfe:"
        ],
        "filename": "iloveme.gif"
    },
    ":partyon:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":partyon:"
        ],
        "filename": "partyon+.gif"
    },
    ":wolke7:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":wolke7:"
        ],
        "filename": "love5.gif"
    },
    ":stecher:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":stecher:"
        ],
        "filename": "stecher.gif"
    },
    ":bart:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":bart:"
        ],
        "filename": "disguise.gif"
    },
    ":rofll:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f616"
        ],
        "filename": ""
    },
    ":trainieren:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f4aa"
        ],
        "filename": ""
    },
    ":sboard:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3c2"
        ],
        "filename": ""
    },
    ":schleimer2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":schleimer2:"
        ],
        "filename": "nerd.gif"
    },
    ":boxer:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":boxer:"
        ],
        "filename": "boxed3_h4h.gif"
    },
    ":ala:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ala:"
        ],
        "filename": "ala.gif"
    },
    ":bike:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":bike:"
        ],
        "filename": "biker_h4h.gif"
    },
    ":lecker:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f60b"
        ],
        "filename": ""
    },
    ":schlafen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":schlafen:"
        ],
        "filename": "456.gif"
    },
    ":rappen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":rappen:"
        ],
        "filename": "rappen.gif"
    },
    ":ohnmacht:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ohnmacht:"
        ],
        "filename": "Ohnmacht1.gif"
    },
    ":wersucht:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":wersucht:"
        ],
        "filename": "wrsucht.gif"
    },
    ":insel:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":insel:"
        ],
        "filename": "Insel.gif"
    },
    ":l\u00fcgen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":l\u00fcgen:"
        ],
        "filename": "pinoccio.gif"
    },
    ":freak:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":freak:"
        ],
        "filename": "smiley-channel.de_schilder173.gif"
    },
    ":schwein:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f437"
        ],
        "filename": ""
    },
    ":lol4:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":lol4:"
        ],
        "filename": "smiley-channel.de_schilder048.gif"
    },
    ":admin:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":admin:"
        ],
        "filename": "admins.gif"
    },
    ":firefox:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":firefox:"
        ],
        "filename": "270.gif"
    },
    ":school:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3eb"
        ],
        "filename": ""
    },
    ":charmant:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3a9"
        ],
        "filename": ""
    },
    ":ausflippen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ausflippen:"
        ],
        "filename": "522.gif"
    },
    ":ww2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ww2:"
        ],
        "filename": "221.gif"
    },
    ":bigeyes:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f440"
        ],
        "filename": ""
    },
    ":kaputtlachen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":kaputtlachen:"
        ],
        "filename": "281.gif"
    },
    ":unschuldig:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f607"
        ],
        "filename": ""
    },
    ":kirche:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "26ea"
        ],
        "filename": ""
    },
    ":frauenklatsch:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f4ac"
        ],
        "filename": ""
    },
    ":krieger:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":krieger:"
        ],
        "filename": "379.gif"
    },
    ":essen2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":essen2:"
        ],
        "filename": "essen.gif"
    },
    ":boese:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f620"
        ],
        "filename": ""
    },
    ":verneigen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":verneigen:"
        ],
        "filename": "verneigen.gif"
    },
    ";-)": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f609"
        ],
        "filename": ""
    },
    ":ja:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f60a-1f44d"
        ],
        "filename": ""
    },
    ":-p": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":-p"
        ],
        "filename": "zunge.gif"
    },
    ":-(": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f620"
        ],
        "filename": ""
    },
    ":nein:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f61f-1f44e"
        ],
        "filename": ""
    },
    ":uncool:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f44e"
        ],
        "filename": ""
    },
    ":klatschen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f44f"
        ],
        "filename": ""
    },
    ":handy:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":handy:"
        ],
        "filename": "handy.gif"
    },
    ":muede:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f62a"
        ],
        "filename": ""
    },
    ":keineahnung:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":keineahnung:"
        ],
        "filename": "keineahnung.gif"
    },
    ":rudolf:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":rudolf:"
        ],
        "filename": "rudolf.gif"
    },
    ":kalt:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f630"
        ],
        "filename": ""
    },
    ":wman:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f385"
        ],
        "filename": ""
    },
    ":zitter:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":zitter:"
        ],
        "filename": "xpb_zitter.gif"
    },
    ":wman2:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f385"
        ],
        "filename": ""
    },
    ":wman3:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":wman3:"
        ],
        "filename": "woswmann1550.gif"
    },
    ":hochzeit:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f492"
        ],
        "filename": ""
    },
    ":oops:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":oops:"
        ],
        "filename": "oops.gif"
    },
    ":kaputthauen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":kaputthauen:"
        ],
        "filename": "kaputthauen.gif"
    },
    ":baden3:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f6c1"
        ],
        "filename": ""
    },
    ":lenak:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":lenak:"
        ],
        "filename": "484.gif"
    },
    ":jeff:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":jeff:"
        ],
        "filename": "Jeff.gif"
    },
    ":knuddell:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":knuddell:"
        ],
        "filename": "knuddel.gif"
    },
    ":ruhe:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ruhe:"
        ],
        "filename": "ruhe.gif"
    },
    ":cool:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f60e"
        ],
        "filename": ""
    },
    ":manweisetnich:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":manweisetnich:"
        ],
        "filename": "man_weiset.png"
    },
    ":(": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":("
        ],
        "filename": "frown.gif"
    },
    ":knuddel2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":knuddel2:"
        ],
        "filename": "liebe_061.gif"
    },
    ":denken:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f614"
        ],
        "filename": ""
    },
    ":denken2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":denken2:"
        ],
        "filename": "Denken2.gif"
    },
    ":denken3:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":denken3:"
        ],
        "filename": "idee.gif"
    },
    ":knuddel3:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":knuddel3:"
        ],
        "filename": "liebe_028.gif"
    },
    ":romantik:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f339"
        ],
        "filename": ""
    },
    ":foto:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":foto:"
        ],
        "filename": "fotosmilie.gif"
    },
    ":sauer2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":sauer2:"
        ],
        "filename": "sauer.gif"
    },
    ":krankes:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f48a"
        ],
        "filename": ""
    },
    ":doof1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":doof1:"
        ],
        "filename": "bin_ich_doof.gif"
    },
    ":car:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f697"
        ],
        "filename": ""
    },
    ":wayne:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":wayne:"
        ],
        "filename": "wayne_interessierts.gif"
    },
    ":snowboard:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3c2"
        ],
        "filename": ""
    },
    ":sagnix:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":sagnix:"
        ],
        "filename": "ich_sag_nix.gif"
    },
    ":regin2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":regin2:"
        ],
        "filename": "hauen.gif"
    },
    ":kuuhl:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":kuuhl:"
        ],
        "filename": "kuuuhl.png"
    },
    ":saugen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":saugen:"
        ],
        "filename": "staubsauger!.gif"
    },
    ":para:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":para:"
        ],
        "filename": "kreis.gif"
    },
    ":blach:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":blach:"
        ],
        "filename": "blach.gif"
    },
    ":rofllll:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":rofllll:"
        ],
        "filename": "smilie_happy_251.gif"
    },
    ":spam:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f38f"
        ],
        "filename": ""
    },
    ":ohnemich:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ohnemich:"
        ],
        "filename": "bpb_ohnemi.gif"
    },
    ":osterkuss:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":osterkuss:"
        ],
        "filename": "o_78-001.gif"
    },
    ":eiermaler:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":eiermaler:"
        ],
        "filename": "ostern_71.gif"
    },
    ":hase:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f430"
        ],
        "filename": ""
    },
    ":hase1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":hase1:"
        ],
        "filename": "hase3.gif"
    },
    ":hase2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":hase2:"
        ],
        "filename": "HASE4.gif"
    },
    ":hase3:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f407"
        ],
        "filename": ""
    },
    ":irre:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":irre:"
        ],
        "filename": "bunny_4.gif"
    },
    ":herz:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "2764"
        ],
        "filename": ""
    },
    ":achja:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":achja:"
        ],
        "filename": "achja.gif"
    },
    ":morg\u00e4hn:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":morg\u00e4hn:"
        ],
        "filename": "morgaehn.gif"
    },
    ":amen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":amen:"
        ],
        "filename": "amen.gif"
    },
    ":aufwachen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":aufwachen:"
        ],
        "filename": "aufwachen.gif"
    },
    ":vio:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":vio:"
        ],
        "filename": "phone02.gif"
    },
    ":admins:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":admins:"
        ],
        "filename": "admin.jpg"
    },
    ":romeo:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":romeo:"
        ],
        "filename": "Romeo.gif"
    },
    ":shy:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f60a"
        ],
        "filename": ""
    },
    ":tbaum:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f384"
        ],
        "filename": ""
    },
    ":kopf:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":kopf:"
        ],
        "filename": "kopf.gif"
    },
    ":closed:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":closed:"
        ],
        "filename": "cl.gif"
    },
    ":deutschland:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1e9-1f1ea"
        ],
        "filename": ""
    },
    ":laugh:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":laugh:"
        ],
        "filename": "deutschland-lacht-ueber-holland.gif"
    },
    ":final:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":final:"
        ],
        "filename": "final04.gif"
    },
    ":wmleo:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":wmleo:"
        ],
        "filename": "wmgoleo.gif"
    },
    ":brasil:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1e7-1f1f7"
        ],
        "filename": ""
    },
    ":fussball:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "26bd"
        ],
        "filename": ""
    },
    ":kopfball:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":kopfball:"
        ],
        "filename": "soccer_2.gif"
    },
    ":rot:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":rot:"
        ],
        "filename": "platzverweis.gif"
    },
    ":leeep:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":leeep:"
        ],
        "filename": "leep.gif"
    },
    ":-[": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":-["
        ],
        "filename": "49_2.gif"
    },
    ":togo:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1f9-1f1ec"
        ],
        "filename": ""
    },
    ":japan:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1ef-1f1f5"
        ],
        "filename": ""
    },
    ":roli:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":roli:"
        ],
        "filename": "boese2.gif"
    },
    ":portugal:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1f5-1f1f9"
        ],
        "filename": ""
    },
    ":meld:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":meld:"
        ],
        "filename": "meld.gif"
    },
    ":moin:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":moin:"
        ],
        "filename": "Moin.gif"
    },
    ":hm:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":hm:"
        ],
        "filename": "hm.gif"
    },
    ":blume:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":blume:"
        ],
        "filename": "6874.gif"
    },
    ":inlove2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":inlove2:"
        ],
        "filename": "huglove.gif"
    },
    ":tess:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1e8-1f1ff"
        ],
        "filename": ""
    },
    ":spanien:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1ea-1f1f8"
        ],
        "filename": ""
    },
    ":angola:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1e6-1f1f4"
        ],
        "filename": ""
    },
    ":Italien:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1ee-1f1f9"
        ],
        "filename": ""
    },
    ":ich:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ich:"
        ],
        "filename": "iiich.gif"
    },
    ":shok:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f62f"
        ],
        "filename": ""
    },
    ":luna:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f431"
        ],
        "filename": ""
    },
    ":holland:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1f3-1f1f1"
        ],
        "filename": ""
    },
    ":gelb:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":gelb:"
        ],
        "filename": "gelb.gif"
    },
    ":weight:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":weight:"
        ],
        "filename": "weight_lift2.gif"
    },
    ":england:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1ec-1f1e7"
        ],
        "filename": ""
    },
    ":ghana:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1ec-1f1ed"
        ],
        "filename": ""
    },
    ":frankreich:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1eb-1f1f7"
        ],
        "filename": ""
    },
    ":spam1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":spam1:"
        ],
        "filename": "spamfrust.gif"
    },
    ":ukraine:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1fa-1f1e6"
        ],
        "filename": ""
    },
    ":2cool:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":2cool:"
        ],
        "filename": "cool3.gif"
    },
    ":rulez:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":rulez:"
        ],
        "filename": "smiley-channel.de_lesen021.gif"
    },
    ":israel:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1ee-1f1f1"
        ],
        "filename": ""
    },
    ":poker:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":poker:"
        ],
        "filename": "poker.gif"
    },
    ":spth:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":spth:"
        ],
        "filename": "spth.png"
    },
    ":JoLo:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":JoLo:"
        ],
        "filename": "MrSax02.gif"
    },
    ":on:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":on:"
        ],
        "filename": "On.gif"
    },
    ":mb:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":mb:"
        ],
        "filename": "eine_wie_keine.png"
    },
    ":boese1:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "261d"
        ],
        "filename": ""
    },
    ":boese2:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f446"
        ],
        "filename": ""
    },
    ":friend:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f46c"
        ],
        "filename": ""
    },
    ":muede1:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f629"
        ],
        "filename": ""
    },
    ":steffi:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":steffi:"
        ],
        "filename": "traurig.gif"
    },
    ":super1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":super1:"
        ],
        "filename": "froh.gif"
    },
    ":ody:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ody:"
        ],
        "filename": "gg!!!!!!!!!!!!!!!!!!!.gif"
    },
    ":halt:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":halt:"
        ],
        "filename": "halt_stop.gif"
    },
    ":lachen1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":lachen1:"
        ],
        "filename": "hand_vorm_mund.gif"
    },
    ":LP:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":LP:"
        ],
        "filename": "ironie.gif"
    },
    ":superman:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":superman:"
        ],
        "filename": "sman.gif"
    },
    ":skater:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":skater:"
        ],
        "filename": "skateboard.gif"
    },
    ":gelb1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":gelb1:"
        ],
        "filename": "sport.gif"
    },
    ":abcheck:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":abcheck:"
        ],
        "filename": "blinkendes_auge_mit_herzchen.gif"
    },
    ":dl:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":dl:"
        ],
        "filename": "diane.gif"
    },
    ":RW:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":RW:"
        ],
        "filename": "rita.gif"
    },
    ":yw:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":yw:"
        ],
        "filename": "fehler.gif"
    },
    ":schild:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":schild:"
        ],
        "filename": "schild.gif"
    },
    ":firefox1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":firefox1:"
        ],
        "filename": "mozilla.gif"
    },
    ":2lee:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":2lee:"
        ],
        "filename": "lee.gif"
    },
    ":pizzaess:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f355"
        ],
        "filename": ""
    },
    ":emoo:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":emoo:"
        ],
        "filename": "emo.gif"
    },
    ":hehe:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":hehe:"
        ],
        "filename": "hehe.gif"
    },
    ":ljena:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ljena:"
        ],
        "filename": "ani_sonstige137.gif"
    },
    ":neugierig:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":neugierig:"
        ],
        "filename": "Neugierig.gif"
    },
    ":F5:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":F5:"
        ],
        "filename": "ani_schilder55.gif"
    },
    ":lachen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":lachen:"
        ],
        "filename": "ani_lachende2.gif"
    },
    ":saugen1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":saugen1:"
        ],
        "filename": "Saugen1.gif"
    },
    ":angi:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":angi:"
        ],
        "filename": "f025.gif"
    },
    ":hau:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":hau:"
        ],
        "filename": "hau.gif"
    },
    ":hust:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":hust:"
        ],
        "filename": "husten.gif"
    },
    ":lolli:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":lolli:"
        ],
        "filename": "lolli.gif"
    },
    ":ranger:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ranger:"
        ],
        "filename": "ranger.gif"
    },
    ":lena87:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":lena87:"
        ],
        "filename": "a020.gif"
    },
    ":partytime:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f389"
        ],
        "filename": ""
    },
    ":graade:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":graade:"
        ],
        "filename": "sta_schilder365.gif"
    },
    ":wishes:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f388"
        ],
        "filename": ""
    },
    ":russ:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f1f7-1f1fa"
        ],
        "filename": ""
    },
    ":sorry:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":sorry:"
        ],
        "filename": "sta_schilder116.gif"
    },
    ":spiegel:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":spiegel:"
        ],
        "filename": "lustich.gif"
    },
    ":wman5:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":wman5:"
        ],
        "filename": "woswmann1560.gif"
    },
    ":wmanlachen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":wmanlachen:"
        ],
        "filename": "woswmann1810.gif"
    },
    ":hannibal:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f482"
        ],
        "filename": ""
    },
    ":sheep:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f411"
        ],
        "filename": ""
    },
    ":grizzly:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f43b"
        ],
        "filename": ""
    },
    ":frauenimforum:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":frauenimforum:"
        ],
        "filename": "frauen_im_forum.gif"
    },
    ":checka:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":checka:"
        ],
        "filename": "peace.gif"
    },
    ":yeah:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":yeah:"
        ],
        "filename": "yeeeah.gif"
    },
    ":klavier:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3b9"
        ],
        "filename": ""
    },
    ":kante:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":kante:"
        ],
        "filename": "bodybuilder.gif"
    },
    ":roflll:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":roflll:"
        ],
        "filename": "roflll.gif"
    },
    ":ohnmacht1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ohnmacht1:"
        ],
        "filename": "ohnmacht.gif"
    },
    ":sylvester:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f386"
        ],
        "filename": ""
    },
    ":keks:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":keks:"
        ],
        "filename": "keks.gif"
    },
    ":radfahrer:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f6b4"
        ],
        "filename": ""
    },
    ":nadia:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":nadia:"
        ],
        "filename": "nadia.gif"
    },
    ":bball:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3c0"
        ],
        "filename": ""
    },
    ":eis:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f366"
        ],
        "filename": ""
    },
    ":geige:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3bb"
        ],
        "filename": ""
    },
    ":qfl\u00f6te:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":qfl\u00f6te:"
        ],
        "filename": "querfloete.gif"
    },
    ":training:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f4aa"
        ],
        "filename": ""
    },
    ":chor:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":chor:"
        ],
        "filename": "schief_singen.gif"
    },
    ":luck:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":luck:"
        ],
        "filename": "good_luck.gif"
    },
    ":otto:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3c6"
        ],
        "filename": ""
    },
    ":diddy:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f941"
        ],
        "filename": ""
    },
    ":isy:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":isy:"
        ],
        "filename": "skuchen.gif"
    },
    ":alex:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":alex:"
        ],
        "filename": "dunce.gif"
    },
    ":shenok:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":shenok:"
        ],
        "filename": "hund.gif"
    },
    ":ade:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ade:"
        ],
        "filename": "ADE_Smily.gif"
    },
    ":dachschaden:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":dachschaden:"
        ],
        "filename": "a085.gif"
    },
    ":yves:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":yves:"
        ],
        "filename": "smilie_sonst_011.gif"
    },
    ":aly:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":aly:"
        ],
        "filename": "c080.gif"
    },
    ":laurie:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":laurie:"
        ],
        "filename": "ups.gif"
    },
    ":blackb:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":blackb:"
        ],
        "filename": "82.gif"
    },
    ":koko:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":koko:"
        ],
        "filename": "c010.gif"
    },
    ":bahnhof:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":bahnhof:"
        ],
        "filename": "bahnhof.gif"
    },
    ":basketball:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "26f9"
        ],
        "filename": ""
    },
    ":boxer1:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f94a"
        ],
        "filename": ""
    },
    ":gitarre:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3b8"
        ],
        "filename": ""
    },
    ":hand:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":hand:"
        ],
        "filename": "haendedruck.gif"
    },
    ":sos:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f198"
        ],
        "filename": ""
    },
    ":krank:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":krank:"
        ],
        "filename": "krank.gif"
    },
    ":krank1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":krank1:"
        ],
        "filename": "krank1.gif"
    },
    ":l\u00e4stern:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":l\u00e4stern:"
        ],
        "filename": "laestern.gif"
    },
    ":k\u00fcsschen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f48f"
        ],
        "filename": ""
    },
    ":willkommen:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":willkommen:"
        ],
        "filename": "Willkommen.gif"
    },
    ":ywsuchti:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ywsuchti:"
        ],
        "filename": "urlaub_lapi.gif"
    },
    ":sun:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f31e"
        ],
        "filename": ""
    },
    ":run:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":run:"
        ],
        "filename": "run.gif"
    },
    ":chris:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":chris:"
        ],
        "filename": "smilie_frech_126.gif"
    },
    ":gassi1:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":gassi1:"
        ],
        "filename": "smilie_tier_142.gif"
    },
    ":olympia:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":olympia:"
        ],
        "filename": "smilie_sp_257.gif"
    },
    ":pico:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":pico:"
        ],
        "filename": "pico.gif"
    },
    ":pray:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f64f"
        ],
        "filename": ""
    },
    ":mimi:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":mimi:"
        ],
        "filename": "smilie_frech_129.gif"
    },
    ":pecora:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":pecora:"
        ],
        "filename": "n030.gif"
    },
    ":achso:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":achso:"
        ],
        "filename": "99.gif"
    },
    ":elliw:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":elliw:"
        ],
        "filename": "smilie_winke_003.gif"
    },
    ":sunchill:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":sunchill:"
        ],
        "filename": "s030.gif"
    },
    ":JoLo1:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3b7"
        ],
        "filename": ""
    },
    ":bl\u00fcmchen:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f490"
        ],
        "filename": ""
    },
    ":grill:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":grill:"
        ],
        "filename": "grillen.gif"
    },
    ":rubin:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":rubin:"
        ],
        "filename": "boast.gif"
    },
    ":gamer:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "1f3ae"
        ],
        "filename": ""
    },
    ":manni:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":manni:"
        ],
        "filename": "smilie_winke_048.gif"
    },
    ":evi:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":evi:"
        ],
        "filename": "smilie_girl_068.gif"
    },
    ":ordi:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":ordi:"
        ],
        "filename": "ordi.gif"
    },
    ":bvb:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":bvb:"
        ],
        "filename": "smilie_bvb.gif"
    },
    ":shy2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":shy2:"
        ],
        "filename": "smilie_girl_066.gif"
    },
    ":deutschland2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":deutschland2:"
        ],
        "filename": "WM.gif"
    },
    ":uschke:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":uschke:"
        ],
        "filename": "3434.gif"
    },
    ":admin2:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":admin2:"
        ],
        "filename": "admins2.gif"
    },
    ":gutebesserung:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":gutebesserung:"
        ],
        "filename": "Gute Besserung.gif"
    },
    ":welcome:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":welcome:"
        ],
        "filename": "welcome.gif"
    },
    ":hotwheel:": {
        "isCanonical": false,
        "isSmiley": false,
        "unicode": [
            "267f"
        ],
        "filename": ""
    },
    ":mokka:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":mokka:"
        ],
        "filename": "mokka.gif"
    },
    ":schalke:": {
        "isCanonical": false,
        "isSmiley": true,
        "unicode": [
            ":schalke:"
        ],
        "filename": "s04fahne.gif"
    }
};
};
